version: '3'
services:
  switch-api:
    build: .
    environment:
     - FLASK_DEBUG=1
     - FLASK_APP=/project/src/server.py
    ports:
     - "5000:80"
    volumes:
     - .:/project
    depends_on:
     - db
  db:
    image: "mongo"
